name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to my EC2
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.TARGET_DIR }}
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: TARGET
          script: |
            cd $TARGET
            git pull origin main
            sudo systemctl restart app-ads-dash
